name: faunadb_sample_project
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  faunadb_data: ^0.0.6
  flutter:
    sdk: flutter
  intl: ^0.17.0
  optional: ^6.1.0+1
  stacked: ^2.2.7
  stacked_services: ^0.8.15

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.5.6
flutter:
  uses-material-design: true

